config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get :signup, to: 'users/registrations#new'
    get :login,  to: 'users/sessions#new'
    get :logout, to: 'users/sessions#destroy'
  end

  root 'top#index'

  namespace :admin do
    root 'top#index'
    post '/:id', to: 'top#update'
  end

  namespace :api do
    resources :attendances
    namespace :admin do
      resources :attendances
    end
  end

end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::ApplicationController
	def index
		@date = date

		attendances = Attendance.where(date: @date).map do |row|
			[row.user_id, row]
		end.to_h

		@rows = User.all.map(&:attributes).map(&:with_indifferent_access).map do |row|
			row[:attendance] = attendances[row[:id]] || Attendance.new
			row
		end
	end

	def update
		attendance = Attendance.find params[:id]
		attendance.update! status: attendance_params[:status]

		redirect_to action: :index, date: attendance.date.strftime(DATE_FORMAT)
	end

	private

	def attendance_params
		params.permit %i[status]
	end

	def date
		Date.strptime params[:date], DATE_FORMAT
	rescue
		Date.today
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	before_action :require_login

	def index
		@date = date
	end

	private

	def date
		Date.strptime params[:date], DATE_FORMAT
	rescue
		Date.today
	end
end

app/views/top/index.html.erb
<div class="container">
	<h3 class="text-center mt-3">日報</h3>
</div>
<hr>
<form action="/api/attendances" method="post">
	<div class="container">
		<%= render 'date_ctrl', date: @date %>
	</div>
	<hr class="mt-0">
	<div id="short-cut-btn" class="d-none">
		<div class="container"><button></button></div>
		<hr>
	</div>
	<div class="container">
		<div id="info" class="d-none"></div>
		<div id="errors" class="alert alert-danger d-none"></div>
		<div class="form-group d-none">
			<div class="input-group">
				<span class="input-group-text">状態</span>
				<input type="text" disabled name="status" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-text">出勤</span>
				<input type="time" step="300" name="start_time" data-btn-text="業務開始" data-btn-type="info" class="form-control">
				<div class="invalid-feedback"></div>
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-text">休憩</span>
				<input type="time" step="300" name="break_time" data-btn-text="休憩開始" data-btn-type="danger" class="form-control">
				<div class="invalid-feedback"></div>
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-text">退勤</span>
				<input type="time" step="300" name="end_time" data-btn-text="業務終了" data-btn-type="primary" class="form-control">
			</div>
			<div class="invalid-feedback"></div>
		</div>
		<div class="form-group">
			<div class="input-group is-invalid mb-3">
				<span class="input-group-text">種別</span>
				<select class="form-select mt-0">
					<option>案件A</option>
					<option>案件B</option>
					<option>案件C</option>
				</select>
			</div>
		</div>
	</div>
	<hr>
	<div class="container">
		<div class="text-center mb-3">
			<!-- <button type="button" class="btn btn-danger btn-lg mx-3">リセット</button> -->
			<button type="submit" class="btn btn-primary btn-lg mx-3" disabled>&nbsp;&nbsp;申請する&nbsp;&nbsp;</button>
		</div>
	</div>
</form>

<hr>

<div class="container text-right">
	<%= link_to 'ログアウトする', logout_path %><br />
</div>